title: Sumyeong Ahn # your name (or website title) here
logo: "/images/picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  sumyeongahn [at] kaist [dot] ac [dot] kr
  <br><br>
  <a href="https://osi.kaist.ac.kr/">Optimization and Statistical Inference Lab</a>, <a href="https://www.kaist.ac.kr/">KAIST</a>, Seoul, South Korea
  <br><br>
  <a href="https://scholar.google.com/citations?user=krxhvIYAAAAJ&hl">Google Scholar</a> / <a href="https://github.com/sumyeongahn/"> Github </a> /  <a href="https://github.com/sumyeongahn.github.io/pdf/CV.pdf"> CV </a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
